name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - Hendri/CI-CD
  pull_request:
    branches:
      - main
      - Hendri/CI-CD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_AUTHOR: ${{ github.actor }}
          GIT_COMMIT: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
        run: npm run test:coverage:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set repo owner lowercase
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        shell: bash

      - name: Build Docker image
        run: docker build -t ghcr.io/${REPO_OWNER_LC}/book-catalog:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${REPO_OWNER_LC}/book-catalog:latest
