name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - Hendri/CI-CD
  pull_request:
    branches:
      - main
      - Hendri/CI-CD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Set repo owner lowercase
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${REPO_OWNER_LC}/book-catalog:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${REPO_OWNER_LC}/book-catalog:latest
